<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Pierre Brigode &amp; Olivier Delaigue" />


<title>Streamflow reconstruction</title>

<script src="site_libs/header-attrs-2.30/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/united.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #204a87; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #8f5902; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #204a87; font-weight: bold; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #ce5c00; font-weight: bold; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>



<style type="text/css">
/* for pandoc --citeproc since 2.11 */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<!-- NOTE: add "navbar-inverse" class for an alternate navbar background -->
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="index.html">airGRteaching</a>
		</div>
		<div id="navbar" class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li><a href="index.html">Home</a></li>
				<li><a href="page_1_get_started_airGRteaching.html">Get Started</a></li>
                <li class="Download">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Exercises<span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li class="dropdown-header">Introduction    </li>
                        <li><a href="page_exo_v00_teaching_hydrology.html"    >Teaching hydrology with airGRteaching        </a></li>
                        <li class="divider"></li>
                        <li class="dropdown-header">English versions</li>
                        <li><a href="page_exo_v01_EN_flow_reconstruction.html">1. Streamflow reconstruction                               </a></li>
						<li><a href="page_exo_v02_EN_flow_forecasting.html"   >2. Low-flow forecasting                                    </a></li>
						<li><a href="page_exo_v03_EN_impact_CC_flow.html"     >3. Impact of climate change on streamflow regime           </a></li>
                        <li class="divider"></li>
                        <li class="dropdown-header">French versions</li>
						<li><a href="page_exo_v01_FR_flow_reconstruction.html">1. Reconstitution de débits                                </a></li>
						<li><a href="page_exo_v02_FR_flow_forecasting.html"   >2. Prévision de bas débits                                 </a></li>
						<li><a href="page_exo_v03_FR_impact_CC_flow.html"     >3. Impact du changement climatique sur le régime des débits</a></li>
					</ul>
				</li>
				<li class="Download">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Download<span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a tabindex="-1" href="https://CRAN.R-project.org/package=airGRteaching" onclick="window.open(this.href); return false;">Package</a></li>
						<li><a tabindex="-1" href="https://CRAN.R-project.org/package=airGRteaching/airGRteaching.pdf" onclick="window.open(this.href); return false;">Manual</a></li>
					</ul>
				</li>
				<li><a href="NEWS.html">News</a></li>
				<li><a href="page_publications.html">Publications</a></li>				
				<li><a href="page_faq.html">FAQ</a></li>
				<li class="Download">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">airGR Galaxy<span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a href="https://hydroGR.github.io/airGR/">airGR R-package</a></li>
						<li><a href="https://CRAN.R-project.org/package=airGRdatasets">airGRdatasets R-package</a></li>
						<li><a href="https://CRAN.R-project.org/package=airGRdatassim">airGRdatassim R-package</a></li>
						<li><a href="https://airgriwrm.g-eau.fr/">airGRiwrm R-package</a></li>
						<li><a href="https://sunshine.inrae.fr/app/airGRmaps">airGRmaps web app</a></li>
					</ul>
				</li>
				<li><a tabindex="-1" href="https://sunshine.inrae.fr/app/airGRteaching" onclick="window.open(this.href); return false;">GUI Demo</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<a href='http://www.inrae.fr/en/' onclick="window.open(this.href); return false;", title="inrae.fr"><img src='fig/logo_inrae_CMJN_square.svg' style='width:45px;height:45px;'></a>
				<a href='https://webgr.inrae.fr/eng/' onclick="window.open(this.href); return false;", title="webgr.inrae.fr"><img src='fig/logo_inrae_hydro_CMJN_square.svg' style='width:45px;height:45px;'></a>
				<a href='https://webgr.inrae.fr/software/airgrteaching/' onclick="window.open(this.href); return false;", title="aiGRteaching"><img src='fig/logo_airGRteaching_CMJN_square.png' style='width:45px;height:45px;'></a>
				<a href='https://gitlab.irstea.fr/HYCAR-Hydro/airgrteaching/' onclick="window.open(this.href); return false;", title="GitLab"><img src='fig/logo_gitlab_CMJN_square.svg' style='width:45px;height:45px;'></a>
			</ul>
		</div><!--/.nav-collapse -->
	</div><!--/.container -->
</div><!--/.navbar -->
<p style ="margin-top: 15px;">
<a href="https://CRAN.R-project.org/package=airGRteaching"><img src="https://www.r-pkg.org/badges/version-ago/airGRteaching" /></a>
<a href="https://www.rdocumentation.org/packages/airGRteaching"><img src="http://cranlogs.r-pkg.org/badges/grand-total/airGRteaching?color=orange" /></a>
<a href="https://www.r-project.org/Licenses/GPL-2">
<svg xmlns="http://www.w3.org/2000/svg" width="095" height="020">
  <linearGradient id="b" x2="0" y2="100%">
    <stop offset="0" stop-opacity=".1" stop-color="#bbb"/>
    <stop offset="1" stop-opacity=".1"/>
  </linearGradient>
  <mask id="a">
    <rect width="095" height="020" rx="3" fill="#fff" />
  </mask>
  <g mask="url(#a)">
    <path fill="#555"    d="M00 0h055v20H00z"/>
    <path fill="#00a3a6" d="M55 0h040v20H55z"/>
    <path fill="url(#b)" d="M00 0h095v20H00z"/>
  </g>
  <g fill="#fff" text-anchor="middle"
     font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">
    <text x="028" y="015" fill="#010101" fill-opacity=".3">
      License
    </text>
    <text x="028" y="014">
      License
    </text>
    <text x="075" y="015" fill="#010101" fill-opacity=".3">
      GPL 2
    </text>
    <text x="075" y="014">
      GPL 2
    </text>
  </g>
</svg>
</a>
<a href="https://doi.org/10.5194/hess-27-3293-2023"><img src="https://img.shields.io/badge/doi-10.5194/hess--27--3293--2023-purple.svg" /></a>
<a href="https://doi.org/10.32614/CRAN.package.airGRteaching"><img src="https://img.shields.io/badge/doi-10.32614/CRAN.package.airGRteaching-purple.svg" /></a>

<!--
<div class="htmlwigetsWarning" style="background-color:#0B9DA0;color:white;padding:10px;">
<b>
Warning:
</b>
<br>
The <b>airGRteaching Shiny GUI</b> launched by the 'ShinyGR' function is sometimes unstable on latest versions of <b>RStudio</b>
<br>
<b>It is better to launch the GUI from the Rgui or from R into a terminal</b>
<br>
</div>

<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" title="1">mirror &lt;-<span class="st"> &quot;https://cran.r-project.org/src/contrib/Archive/htmlwidgets&quot;</span></a>
<a class="sourceLine" id="cb2-2" title="2"><span class="kw">install.packages</span>(<span class="dt">pkgs =</span> <span class="kw">file.path</span>(mirror, <span class="st">&quot;htmlwidgets_1.3.tar.gz&quot;</span>),</a>
<a class="sourceLine" id="cb2-3" title="3">                 <span class="dt">repos =</span> <span class="ot">NULL</span>, <span class="dt">type =</span> <span class="st">&quot;source&quot;</span>)</a></code></pre></div>
</div>
-->
</p>


<div id="header">



<h1 class="title toc-ignore">Streamflow reconstruction</h1>
<h4 class="author">Pierre Brigode &amp; Olivier Delaigue</h4>

</div>


<div id="objective" class="section level1" number="1">
<h1><span class="header-section-number">1</span> Objective</h1>
<div id="context" class="section level2" number="1.1">
<h2><span class="header-section-number">1.1</span> Context</h2>
<p>The L’Esteron au Broc [La Clave] is a catchment of 442 km² for which
measured streamflows are available from 1999 to 2018, but with missing
data (e.g. for the year 2014).</p>
<p>The exercise consists in using the hydro-climatic data available on
the catchment and a rainfall-runoff model to reconstitute the missing
data through hydrological simulation (see following figure). To do this,
we must first ensure, through a calibration-evaluation procedure, that
the model has a sufficient level of performance to carry out this
reconstruction exercise.</p>
<p>This work will be performed in four steps:</p>
<ol style="list-style-type: decimal">
<li>Manual calibration of the rainfall-runoff model (over the so-called
“calibration” period)</li>
<li>Automatic calibration of the rainfall-runoff model (over the
“calibration” period).</li>
<li>Evaluation of the obtained parameter sets (over the “evaluation”
period).</li>
<li>Hydrological reconstruction by rainfall-runoff modelling (during the
“simulation” period).</li>
</ol>
<p><img src="figure/v01_fig_presentation-1.png" width="98%" /></p>
</div>
<div id="instructions" class="section level2" number="1.2">
<h2><span class="header-section-number">1.2</span> Instructions</h2>
<p>This section aims to define the calibration and simulation conditions
of the hydrological model (parameter calibration period, model
initialization period, calibration criterion, etc.).</p>
<div id="rainfall-runoff-model" class="section level3" number="1.2.1">
<h3><span class="header-section-number">1.2.1</span> Rainfall-runoff
model</h3>
<p>You will used the GR2M model <span class="citation">(Mouelhi et al.
2006)</span>. It is a conceptual and lumped rainfall-runoff model,
operating on a monthly time step and having two parameters. It requires
as input continuous time series of monthly precipitation and potential
evapotranspiration.</p>
<p>This model is easily usable thanks to the
<strong><font color="#0BA6AA">airGRteaching</font></strong> package
<span class="citation">(Delaigue et al. 2025, 2023)</span>, developped
for the <a href="https://cran.r-project.org/">R software</a> by the <a
href="https://webgr.inrae.fr/eng/">Catchment Hydrology research group of
the HYCAR research unit</a> (<a
href="https://www.inrae.fr/en">INRAE</a>, France).</p>
<p>The time series of observed precipitation, PE and streamflow can be
easily formatted using the <code>PrepGR()</code> function. A
rainfall-runoff simulation can be performed with the
<code>SimGR()</code> function, an a parameter calibration using the
<code>CalGR()</code>.</p>
</div>
<div id="calibration-and-warm-up-period" class="section level3"
number="1.2.2">
<h3><span class="header-section-number">1.2.2</span> Calibration (and
warm-up) period</h3>
<p>GR2M, like many conceptual rainfall-runoff models, consists of
conceptual reservoirs, whose initial levels at the beginning of the
simulation are unknown and cannot be estimated by measurement. These
initial levels must therefore be chosen arbitrarily (or based on an a
priori). This can induce large errors in the model in the case where the
estimated initial conditions deviate from what they should be according
to the previous climatic conditions. To limit these errors, a warm-up
period is generally considered. This period, which precedes the
simulation period, is used to ensure that the levels in the reservoirs
are independent of the initial conditions. It must therefore be longer
than the memory of the catchment at the previous climatic conditions. In
many catchments, this memory of previous conditions does not exceed one
year, but in others that have a multi-year behavior, for example because
of groundwater, it may be necessary to consider several years for the
initialization of the model. During this warm-up period, the model
errors are not used in the calculation of the performance criteria. This
means that it is not necessary to have observed streamflow data over the
warm-up period, only climate data are necessary.</p>
<p>In this exercise, a period of 24 months will be considered, starting
in January 2003 and ending in December 2004. The next time step (January
2005) will be the first time step of the model calibration.</p>
<p>The period to be considered for the calibration of the GR2M
parameters on the L’Esteron au Broc [La Clave] catchment starts in
January 2005 and ends in December 2010.</p>
</div>
<div id="calibration-criteria" class="section level3" number="1.2.3">
<h3><span class="header-section-number">1.2.3</span> Calibration
criteria</h3>
<p>The calibration criterion to be considered in this exercise is the
Nash and Sutcliffe criterion <span class="citation">(Nash and Sutcliffe
1970)</span>, noted <span class="math inline">\(NSE\)</span> hereafter
(see following equation). This criterion is widely used in hydrological
modelling.</p>
<p>The NSE criterion, bounded between <span
class="math inline">\(-\infty\)</span> and <span
class="math inline">\(1\)</span>, allows to quantify the performance of
a model in a relative way, by comparing a series of simulated
streamflows with a so-called “naive” model, here the average of the
observed streamflows (i.e. a series of streamflows constituted in each
time step by the average of the observed streamflows). Thus, a NSE value
equal to 1 indicates a perfect agreement between the series of observed
and simulated streamflows (which is never the case), whereas a NSE value
lower than 0 means that the simulation considered is less efficient than
the simulation of the “naive” model. The calculation of <span
class="math inline">\(NSE\)</span> is detailed in the following
equation, where <span class="math inline">\(Q_{obs,t}\)</span> is the
observed streamflow at time step <span class="math inline">\(t\)</span>,
<span class="math inline">\(Q_{sim,t}\)</span> is the simulated
streamflow at time step <span class="math inline">\(t\)</span>, <span
class="math inline">\(\overline{Q_{obs}}\)</span> is the average of the
observed streamflows, and <span class="math inline">\(n\)</span> is the
number of observations:</p>
<p><span class="math display">\[\begin{equation}
NSE =
1-\frac{\sum_{t=1}^{n}(Q_{obs,t}-Q_{sim,t})^{2}}{\sum_{t=1}^{n}(Q_{obs,t}-\overline{Q_{obs}})^{2}}
\end{equation}\]</span></p>
<p>The elements necessary for the calculation of the calibration
criterion have to be set as arguments of the <code>CalGR()</code>
function.</p>
</div>
<div id="manual-estimation-of-gr2m-parameters" class="section level3"
number="1.2.4">
<h3><span class="header-section-number">1.2.4</span> Manual estimation
of GR2M parameters</h3>
<p>This task, which can be tedious (but very formative) and requires a
certain expertise, is to be carried out by testing several sets of GR2M
parameters and by analyzing the quality of the simulations produced over
the calibration period. In this exercise, a maximum of 10 sets of model
parameters will be tested. The first set of parameters to be tested is
composed of the median values of the GR2M parameters, defined by <span
class="citation">Mouelhi et al. (2006)</span> after numerous
calibrations of the model on different catchments. These values as well
as the associated bounds of variation are equal to:</p>
<ul>
<li>X1 : 380 [mm] (140 [mm] <span class="math inline">\(\leq\)</span> X1
<span class="math inline">\(\leq\)</span> 2640 [mm]) ;</li>
<li>X2 : 0.92 [-] (0.21 [-] <span class="math inline">\(\leq\)</span> X2
<span class="math inline">\(\leq\)</span> 1.31 [-]).</li>
</ul>
</div>
<div id="automatic-calibration-of-gr2m-parameters"
class="section level3" number="1.2.5">
<h3><span class="header-section-number">1.2.5</span> Automatic
calibration of GR2M parameters</h3>
<p>Automatic parameter estimation aims at using a search algorithm in
the parameter space. This algorithm will automatically generate sets of
parameters, test them, and generate others according to the performance
of those already tested, until converging to an optimum. The algorithm
developed by <span class="citation">Michel (1991)</span> will be used in
this exercise.</p>
</div>
<div id="evaluation-period" class="section level3" number="1.2.6">
<h3><span class="header-section-number">1.2.6</span> Evaluation
period</h3>
<p>The evaluation period is a period on which a model previously
calibrated on another period is applied. This is a classic way of using
a model, which is confronted with unknown situations. The independence
of the evaluation period from the calibration period ensures that the
model does not benefit from already known information. The objective of
this test is to evaluate if the model is able to maintain the same level
of performance (and therefore error) under new climatic conditions as
those encountered during calibration. If so, we can estimate that the
parameters of the model depend little on the conditions of the
calibration period and therefore that the model is transposable to
different conditions (we say that it is robust). If not, we must
understood the causes of this decrease in performance.</p>
<p>Over this evaluation period, we can evaluate the model performance
using the same criterion as the one used for calibration, but we can
also complete the analysis using other criteria.</p>
<p>In this exercise, the evaluation period will start in January 2011,
end in December 2018, and will be preceded by an warm-up period starting
in January 2009 and ending in December 2010.</p>
</div>
<div id="simulation-period" class="section level3" number="1.2.7">
<h3><span class="header-section-number">1.2.7</span> Simulation
period</h3>
<p>The final aims of this exercise is to reconstruct the streamflows of
the catchment for the months without measurements using simulated
streamflows. In order to have a single simulation covering the entire
study period, this simulation will start in January 2001 and end in
December 2018, with a warm-up period of 24 months starting in January
January 1999 and ending in December 2000.</p>
</div>
</div>
<div id="data-available" class="section level2" number="1.3">
<h2><span class="header-section-number">1.3</span> Data available</h2>
<p>The data set available to the rainfall-runoff modelling consists
of:</p>
<ul>
<li>a time series of daily total precipitation (liquid + solid) [mm/day]
(<code>Ptot</code>);</li>
<li>a time series of daily potential evapotranspiration calculated with
the <span class="citation">Oudin et al. (2005)</span> formula [mm/day]
(<code>Evap</code>);</li>
<li>a time series of daily streamflows expressed as a specific discharge
[mm/day] (<code>Qmmd</code>).</li>
</ul>
<p>The daily time series can be aggregated to a monthly time step using
the <code>SeriesAggreg()</code> function.</p>
</div>
</div>
<div id="command-lines-for-the-production-of-simulations"
class="section level1" number="2">
<h1><span class="header-section-number">2</span> Command lines for the
production of simulations</h1>
<div id="loading-and-formatting-of-data" class="section level2"
number="2.1">
<h2><span class="header-section-number">2.1</span> Loading and
formatting of data</h2>
<p>The following command lines allow to read the data necessary for the
calibration of the GR2M rainfall-runoff model and to define the
considered temporal periods (warm-up period, calibration period and
evaluation period):</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="co"># Catchment data loading</span></span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a><span class="fu">library</span>(airGRdatasets)</span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;Y643401001&quot;</span>, <span class="at">package =</span> <span class="st">&quot;airGRdatasets&quot;</span>)</span>
<span id="cb1-4"><a href="#cb1-4" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" tabindex="-1"></a><span class="co"># Catchment metadata</span></span>
<span id="cb1-6"><a href="#cb1-6" tabindex="-1"></a><span class="fu">str</span>(Y643401001<span class="sc">$</span>Meta)</span></code></pre></div>
<pre><code>## List of 4
##  $ Code:List of 2
##   ..$ H3: chr &quot;Y643401001&quot;
##   ..$ H2: chr &quot;Y6434010&quot;
##  $ Name: chr &quot;L&#39;Esteron au Broc [La Clave]&quot;
##  $ Coor:List of 2
##   ..$ X: num 7.16
##   ..$ Y: num 43.8
##  $ Area: num 442</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" tabindex="-1"></a><span class="co"># Observed daily time series</span></span>
<span id="cb3-2"><a href="#cb3-2" tabindex="-1"></a>ts_obs_d <span class="ot">&lt;-</span> Y643401001<span class="sc">$</span>TS</span>
<span id="cb3-3"><a href="#cb3-3" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" tabindex="-1"></a><span class="co"># Summary of the time series</span></span>
<span id="cb3-5"><a href="#cb3-5" tabindex="-1"></a><span class="fu">summary</span>(ts_obs_d)</span></code></pre></div>
<pre><code>##       Date                 Ptot              Temp            Evap            Qls              Qmmd       
##  Min.   :1999-01-01   Min.   :  0.000   Min.   :-7.20   Min.   :0.000   Min.   :   790   Min.   : 0.154  
##  1st Qu.:2004-01-01   1st Qu.:  0.000   1st Qu.: 5.20   1st Qu.:0.600   1st Qu.:  1830   1st Qu.: 0.357  
##  Median :2008-12-31   Median :  0.000   Median :10.40   Median :1.700   Median :  3100   Median : 0.605  
##  Mean   :2008-12-31   Mean   :  2.934   Mean   :10.69   Mean   :1.989   Mean   :  6303   Mean   : 1.231  
##  3rd Qu.:2013-12-31   3rd Qu.:  1.200   3rd Qu.:16.30   3rd Qu.:3.300   3rd Qu.:  6990   3rd Qu.: 1.365  
##  Max.   :2018-12-31   Max.   :146.300   Max.   :27.20   Max.   :5.300   Max.   :167000   Max.   :32.611  
##                                                                         NA&#39;s   :136      NA&#39;s   :136</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" tabindex="-1"></a><span class="co"># Calibration period</span></span>
<span id="cb5-2"><a href="#cb5-2" tabindex="-1"></a>per_cal_wup <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;2003-01-01&quot;</span>, <span class="st">&quot;2004-12-01&quot;</span>)</span>
<span id="cb5-3"><a href="#cb5-3" tabindex="-1"></a>per_cal_run <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;2005-01-01&quot;</span>, <span class="st">&quot;2010-12-01&quot;</span>)</span>
<span id="cb5-4"><a href="#cb5-4" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" tabindex="-1"></a><span class="co"># Evaluation period </span></span>
<span id="cb5-6"><a href="#cb5-6" tabindex="-1"></a>per_eva_wup <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;2009-01-01&quot;</span>, <span class="st">&quot;2010-12-01&quot;</span>)</span>
<span id="cb5-7"><a href="#cb5-7" tabindex="-1"></a>per_eva_run <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;2011-01-01&quot;</span>, <span class="st">&quot;2018-12-01&quot;</span>)</span>
<span id="cb5-8"><a href="#cb5-8" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" tabindex="-1"></a><span class="co"># Simulation period</span></span>
<span id="cb5-10"><a href="#cb5-10" tabindex="-1"></a>per_sim_wup <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;1999-01-01&quot;</span>, <span class="st">&quot;2000-12-01&quot;</span>)</span>
<span id="cb5-11"><a href="#cb5-11" tabindex="-1"></a>per_sim_run <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;2001-01-01&quot;</span>, <span class="st">&quot;2018-12-01&quot;</span>)</span></code></pre></div>
</div>
<div id="preparing-the-data-for-gr2m" class="section level2"
number="2.2">
<h2><span class="header-section-number">2.2</span> Preparing the data
for GR2M</h2>
<p>The following command lines are intended to prepare the available
data for use by GR2M, using the <code>SeriesAggreg()</code> and
<code>PrepGR()</code> functions.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" tabindex="-1"></a><span class="co"># Monthly aggregation of observed daily time series</span></span>
<span id="cb6-2"><a href="#cb6-2" tabindex="-1"></a>ts_obs_m <span class="ot">&lt;-</span> <span class="fu">SeriesAggreg</span>(ts_obs_d[, <span class="fu">c</span>(<span class="st">&quot;Date&quot;</span>, <span class="st">&quot;Ptot&quot;</span>, <span class="st">&quot;Evap&quot;</span>, <span class="st">&quot;Qmmd&quot;</span>, <span class="st">&quot;Temp&quot;</span>)],</span>
<span id="cb6-3"><a href="#cb6-3" tabindex="-1"></a>                         <span class="at">Format =</span> <span class="st">&quot;%Y%m&quot;</span>,</span>
<span id="cb6-4"><a href="#cb6-4" tabindex="-1"></a>                         <span class="at">ConvertFun =</span> <span class="fu">c</span>(<span class="st">&quot;sum&quot;</span>, <span class="st">&quot;sum&quot;</span>, <span class="st">&quot;sum&quot;</span>, <span class="st">&quot;mean&quot;</span>))</span></code></pre></div>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" tabindex="-1"></a><span class="co"># Data processing for GR2M</span></span>
<span id="cb7-2"><a href="#cb7-2" tabindex="-1"></a>prep <span class="ot">&lt;-</span> <span class="fu">PrepGR</span>(<span class="at">DatesR     =</span> ts_obs_m<span class="sc">$</span>Date,</span>
<span id="cb7-3"><a href="#cb7-3" tabindex="-1"></a>               <span class="at">Precip     =</span> ts_obs_m<span class="sc">$</span>Ptot,</span>
<span id="cb7-4"><a href="#cb7-4" tabindex="-1"></a>               <span class="at">PotEvap    =</span> ts_obs_m<span class="sc">$</span>Evap, </span>
<span id="cb7-5"><a href="#cb7-5" tabindex="-1"></a>               <span class="at">Qobs       =</span> ts_obs_m<span class="sc">$</span>Qmmd,</span>
<span id="cb7-6"><a href="#cb7-6" tabindex="-1"></a>               <span class="at">HydroModel =</span> <span class="st">&quot;GR2M&quot;</span>, </span>
<span id="cb7-7"><a href="#cb7-7" tabindex="-1"></a>               <span class="at">CemaNeige  =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
</div>
<div id="manual-calibration" class="section level2" number="2.3">
<h2><span class="header-section-number">2.3</span> Manual
calibration</h2>
<p>The following command lines illustrate the steps required to perform
a rainfall-runoff simulation using a given set of parameters (here the
set of default values of GR2M) and to calculate the NSE criterion
associated with this simulation.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" tabindex="-1"></a><span class="co"># Parameter set to test</span></span>
<span id="cb8-2"><a href="#cb8-2" tabindex="-1"></a>i_param_gr2m <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">X1 =</span> <span class="dv">380</span>, <span class="at">X2 =</span> <span class="fl">0.92</span>)</span>
<span id="cb8-3"><a href="#cb8-3" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" tabindex="-1"></a><span class="co"># Simulation over the calibration period</span></span>
<span id="cb8-5"><a href="#cb8-5" tabindex="-1"></a>i_sim_manu <span class="ot">&lt;-</span> <span class="fu">SimGR</span>(<span class="at">PrepGR  =</span> prep, </span>
<span id="cb8-6"><a href="#cb8-6" tabindex="-1"></a>                    <span class="at">Param   =</span> i_param_gr2m,</span>
<span id="cb8-7"><a href="#cb8-7" tabindex="-1"></a>                    <span class="at">EffCrit =</span> <span class="st">&quot;NSE&quot;</span>,</span>
<span id="cb8-8"><a href="#cb8-8" tabindex="-1"></a>                    <span class="at">WupPer  =</span> per_cal_wup, </span>
<span id="cb8-9"><a href="#cb8-9" tabindex="-1"></a>                    <span class="at">SimPer  =</span> per_cal_run,</span>
<span id="cb8-10"><a href="#cb8-10" tabindex="-1"></a>                    <span class="at">verbose =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Warning in CreateIniStates(FUN_MOD = FUN_MOD, InputsModel = InputsModel, : &#39;RunModel_GR2M&#39; does not require
## &#39;ExpStore&#39;. Value set to NA</code></pre>
<pre><code>## Warning in CreateIniStates(FUN_MOD = FUN_MOD, InputsModel = InputsModel, : &#39;RunModel_GR2M&#39; does not require
## &#39;IntStore&#39;. Values set to NA</code></pre>
<pre><code>## Warning in CreateIniStates(FUN_MOD = FUN_MOD, InputsModel = InputsModel, : &#39;RunModel_GR2M&#39; does not require
## &#39;GCemaNeigeLayers&#39; &#39;GCemaNeigeLayers&#39;, &#39;GthrCemaNeigeLayers&#39; and &#39;GlocmaxCemaNeigeLayers&#39;. Values set to NA</code></pre>
<pre><code>## Crit. NSE[Q] = 0.8133</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" tabindex="-1"></a><span class="co"># Calibration criterion</span></span>
<span id="cb13-2"><a href="#cb13-2" tabindex="-1"></a><span class="fu">GetCrit</span>(i_sim_manu)</span></code></pre></div>
<pre><code>##    NSE[Q] 
## 0.8132615</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" tabindex="-1"></a><span class="co"># Graphical assessment of the calibration performance</span></span>
<span id="cb15-2"><a href="#cb15-2" tabindex="-1"></a><span class="fu">plot</span>(i_sim_manu)</span></code></pre></div>
<p><img src="figure/v01_fig_cal_manu_gr2m-1.png" width="98%" /></p>
<p>The first set of parameters tested (default GR2M values) gives an NSE
criterion of 0.813, which is a good overall performance. The precedent
figure allows us to compare the simulation obtained with the observed
streamflows.</p>
<p>Now it’s your turn to play! The game consists in testing different
values of the GR2M parameters, to perform a simulation and to calculate
the NSE criterion for each tested set in order to identify the set that
seems to be optimal. For each parameter, plot the evolution of the
“objective” function versus the parameter value. The analysis of the
simulated hydrographs, coupled with the comparison of NSE values, will
allow to “guide” the modification of the parameters values. To do so,
you can embed the previous code in a loop. At each iteration you test a
new parameter set and compute the corresponding criterion. This way you
can find the “best” parameter set.</p>
</div>
<div id="automatic-calibration" class="section level2" number="2.4">
<h2><span class="header-section-number">2.4</span> Automatic
calibration</h2>
<p>The following command lines allow the GR2M model to be calibrated
over the so-called “calibration” period.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" tabindex="-1"></a><span class="co"># Calibration</span></span>
<span id="cb16-2"><a href="#cb16-2" tabindex="-1"></a>cal_auto <span class="ot">&lt;-</span> <span class="fu">CalGR</span>(<span class="at">PrepGR  =</span> prep, </span>
<span id="cb16-3"><a href="#cb16-3" tabindex="-1"></a>                  <span class="at">CalCrit =</span> <span class="st">&quot;NSE&quot;</span>,</span>
<span id="cb16-4"><a href="#cb16-4" tabindex="-1"></a>                  <span class="at">WupPer  =</span> per_cal_wup, </span>
<span id="cb16-5"><a href="#cb16-5" tabindex="-1"></a>                  <span class="at">CalPer  =</span> per_cal_run,</span>
<span id="cb16-6"><a href="#cb16-6" tabindex="-1"></a>                  <span class="at">verbose =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Warning in CreateIniStates(FUN_MOD = FUN_MOD, InputsModel = InputsModel, : &#39;RunModel_GR2M&#39; does not require
## &#39;ExpStore&#39;. Value set to NA</code></pre>
<pre><code>## Warning in CreateIniStates(FUN_MOD = FUN_MOD, InputsModel = InputsModel, : &#39;RunModel_GR2M&#39; does not require
## &#39;IntStore&#39;. Values set to NA</code></pre>
<pre><code>## Warning in CreateIniStates(FUN_MOD = FUN_MOD, InputsModel = InputsModel, : &#39;RunModel_GR2M&#39; does not require
## &#39;GCemaNeigeLayers&#39; &#39;GCemaNeigeLayers&#39;, &#39;GthrCemaNeigeLayers&#39; and &#39;GlocmaxCemaNeigeLayers&#39;. Values set to NA</code></pre>
<pre><code>## Grid-Screening in progress (0% 20% 40% 60% 80% 100%)
##   Screening completed (9 runs)
##       Param =  347.234,    0.907
##       Crit. NSE[Q]       = 0.8022
## Steepest-descent local search in progress
##   Calibration completed (17 iterations, 72 runs)
##       Param =  639.061,    0.930
##       Crit. NSE[Q]       = 0.8558</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" tabindex="-1"></a><span class="co"># Graphical assessment of the calibration performance</span></span>
<span id="cb21-2"><a href="#cb21-2" tabindex="-1"></a><span class="fu">plot</span>(cal_auto)</span></code></pre></div>
<p><img src="figure/v01_fig_cal_auto_gr2m-1.png" width="98%" /></p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" tabindex="-1"></a><span class="co"># Get parameter values</span></span>
<span id="cb22-2"><a href="#cb22-2" tabindex="-1"></a>param_cal <span class="ot">&lt;-</span> <span class="fu">GetParam</span>(cal_auto)</span>
<span id="cb22-3"><a href="#cb22-3" tabindex="-1"></a>param_cal</span></code></pre></div>
<pre><code>## [1] 639.0611   0.9300</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" tabindex="-1"></a><span class="co"># Get criterion value</span></span>
<span id="cb24-2"><a href="#cb24-2" tabindex="-1"></a><span class="fu">GetCrit</span>(cal_auto)</span></code></pre></div>
<pre><code>##    NSE[Q] 
## 0.8558419</code></pre>
<p>The two parameters and the value of the calibration criterion (<span
class="math inline">\(NSE\)</span>) obtained after the automatic
calibration procedure are:</p>
<ul>
<li>X1 = 639 [mm]</li>
<li>X2 = 0.93 [-]</li>
<li><span class="math inline">\(NSE\)</span> = 0.856 [-]</li>
</ul>
<p>The performance obtained in calibration is considered good, with a
criterion <span class="math inline">\(NSE\)</span> equal to 0.856.</p>
<p>The following command lines allow to store in the same table the
observed streamflows and the simulated streamflows with the set of
parameters obtained by automatic calibration, in order to compare
them.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" tabindex="-1"></a><span class="co"># Combination of observed and simulated streamflow time series on the calibration period</span></span>
<span id="cb26-2"><a href="#cb26-2" tabindex="-1"></a>ts_cal <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(cal_auto)</span>
<span id="cb26-3"><a href="#cb26-3" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" tabindex="-1"></a><span class="co"># Combination of observed and simulated streamflow time series on the entire period</span></span>
<span id="cb26-5"><a href="#cb26-5" tabindex="-1"></a>ts_cal_all <span class="ot">&lt;-</span> <span class="fu">merge</span>(<span class="at">x =</span> ts_obs_m[, <span class="st">&quot;Date&quot;</span>, <span class="at">drop =</span> <span class="cn">FALSE</span>], <span class="at">y =</span> ts_cal, </span>
<span id="cb26-6"><a href="#cb26-6" tabindex="-1"></a>                    <span class="at">by.x =</span> <span class="st">&quot;Date&quot;</span>, <span class="at">by.y =</span> <span class="st">&quot;Dates&quot;</span>, </span>
<span id="cb26-7"><a href="#cb26-7" tabindex="-1"></a>                    <span class="at">all.x =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>The following figure shows the observed and simulated streamflow
series over the calibration period.</p>
<p><img src="figure/v01_fig_cal-1.png" width="98%" /></p>
</div>
<div id="evaluation" class="section level2" number="2.5">
<h2><span class="header-section-number">2.5</span> Evaluation</h2>
<p>The following command lines allow us to use the parameter set
obtained by automatic calibration to carry out a simulation over the
evaluation period (2011-2018) and to calculate the score <span
class="math inline">\(NSE\)</span> associated with this simulation. This
score constitutes the evaluation performance of the model.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" tabindex="-1"></a><span class="co"># Simulation over the evaluation period</span></span>
<span id="cb27-2"><a href="#cb27-2" tabindex="-1"></a>eva <span class="ot">&lt;-</span> <span class="fu">SimGR</span>(<span class="at">PrepGR  =</span> prep, </span>
<span id="cb27-3"><a href="#cb27-3" tabindex="-1"></a>             <span class="at">Param   =</span> param_cal,</span>
<span id="cb27-4"><a href="#cb27-4" tabindex="-1"></a>             <span class="at">WupPer  =</span> per_eva_wup, </span>
<span id="cb27-5"><a href="#cb27-5" tabindex="-1"></a>             <span class="at">SimPer  =</span> per_eva_run,</span>
<span id="cb27-6"><a href="#cb27-6" tabindex="-1"></a>             <span class="at">EffCrit =</span> <span class="st">&quot;NSE&quot;</span>,</span>
<span id="cb27-7"><a href="#cb27-7" tabindex="-1"></a>             <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## Warning in CreateIniStates(FUN_MOD = FUN_MOD, InputsModel = InputsModel, : &#39;RunModel_GR2M&#39; does not require
## &#39;ExpStore&#39;. Value set to NA</code></pre>
<pre><code>## Warning in CreateIniStates(FUN_MOD = FUN_MOD, InputsModel = InputsModel, : &#39;RunModel_GR2M&#39; does not require
## &#39;IntStore&#39;. Values set to NA</code></pre>
<pre><code>## Warning in CreateIniStates(FUN_MOD = FUN_MOD, InputsModel = InputsModel, : &#39;RunModel_GR2M&#39; does not require
## &#39;GCemaNeigeLayers&#39; &#39;GCemaNeigeLayers&#39;, &#39;GthrCemaNeigeLayers&#39; and &#39;GlocmaxCemaNeigeLayers&#39;. Values set to NA</code></pre>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" tabindex="-1"></a><span class="co"># Get the criterion value</span></span>
<span id="cb31-2"><a href="#cb31-2" tabindex="-1"></a><span class="fu">GetCrit</span>(eva)</span></code></pre></div>
<pre><code>##    NSE[Q] 
## 0.8642077</code></pre>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" tabindex="-1"></a><span class="co"># Combination of observed and simulated streamflow time series</span></span>
<span id="cb33-2"><a href="#cb33-2" tabindex="-1"></a>ts_eva <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(eva)</span></code></pre></div>
<p>The performance obtained by the model in evaluation is 0.864.</p>
<p>The following figure represents the observed and simulated streamflow
series over the evaluation period.</p>
<p><img src="figure/v01_fig_eval-1.png" width="98%" /></p>
</div>
<div id="reconstitution" class="section level2" number="2.6">
<h2><span class="header-section-number">2.6</span> Reconstitution</h2>
<p>The following command lines allow the use of the parameters obtained
by automatic calibration to simulate the streamflow over the entire
period studied.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" tabindex="-1"></a><span class="co"># Simulation over the entire period</span></span>
<span id="cb34-2"><a href="#cb34-2" tabindex="-1"></a>sim <span class="ot">&lt;-</span> <span class="fu">SimGR</span>(<span class="at">PrepGR  =</span> prep, </span>
<span id="cb34-3"><a href="#cb34-3" tabindex="-1"></a>             <span class="at">Param   =</span> param_cal,</span>
<span id="cb34-4"><a href="#cb34-4" tabindex="-1"></a>             <span class="at">WupPer  =</span> per_sim_wup, </span>
<span id="cb34-5"><a href="#cb34-5" tabindex="-1"></a>             <span class="at">SimPer  =</span> per_sim_run,</span>
<span id="cb34-6"><a href="#cb34-6" tabindex="-1"></a>             <span class="at">EffCrit =</span> <span class="st">&quot;NSE&quot;</span>,</span>
<span id="cb34-7"><a href="#cb34-7" tabindex="-1"></a>             <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## Warning in CreateIniStates(FUN_MOD = FUN_MOD, InputsModel = InputsModel, : &#39;RunModel_GR2M&#39; does not require
## &#39;ExpStore&#39;. Value set to NA</code></pre>
<pre><code>## Warning in CreateIniStates(FUN_MOD = FUN_MOD, InputsModel = InputsModel, : &#39;RunModel_GR2M&#39; does not require
## &#39;IntStore&#39;. Values set to NA</code></pre>
<pre><code>## Warning in CreateIniStates(FUN_MOD = FUN_MOD, InputsModel = InputsModel, : &#39;RunModel_GR2M&#39; does not require
## &#39;GCemaNeigeLayers&#39; &#39;GCemaNeigeLayers&#39;, &#39;GthrCemaNeigeLayers&#39; and &#39;GlocmaxCemaNeigeLayers&#39;. Values set to NA</code></pre>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" tabindex="-1"></a><span class="co"># Get the criterion value</span></span>
<span id="cb38-2"><a href="#cb38-2" tabindex="-1"></a><span class="fu">GetCrit</span>(sim)</span></code></pre></div>
<pre><code>##  NSE[Q] 
## 0.84484</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" tabindex="-1"></a><span class="co"># Combination of observed and simulated streamflow time series</span></span>
<span id="cb40-2"><a href="#cb40-2" tabindex="-1"></a>ts_sim <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(sim)</span></code></pre></div>
<p>The results of the final simulation are shown in the following
figure.</p>
<p><img src="figure/v01_fig_sim-1.png" width="98%" /></p>
</div>
</div>
<div id="references" class="section level1 unnumbered">
<h1 class="unnumbered">References</h1>
<div id="refs" class="references csl-bib-body hanging-indent"
entry-spacing="0">
<div id="ref-airGRteaching_art" class="csl-entry">
Delaigue, O., P. Brigode, G. Thirel, and L. Coron. 2023. <span>“<span
class="nocase">airGRteaching</span>: An Open-Source Tool for Teaching
Hydrological Modeling with <span>R</span>.”</span> <em>Hydrology and
Earth System Sciences</em> 27 (17): 3293–3327. <a
href="https://doi.org/10.5194/hess-27-3293-2023">https://doi.org/10.5194/hess-27-3293-2023</a>.
</div>
<div id="ref-airGRteaching_man" class="csl-entry">
Delaigue, O., L. Coron, P. Brigode, and G. Thirel. 2025. <em><span
class="nocase">airGRteaching</span>: Teaching Hydrological Modelling
with <span>GR</span> (<span>Shiny</span> Interface Included)</em>. <em>R
News</em>. <a
href="https://doi.org/10.32614/CRAN.package.airGRteaching">https://doi.org/10.32614/CRAN.package.airGRteaching</a>.
</div>
<div id="ref-michel_hydrologie_1991" class="csl-entry">
Michel, C. 1991. <em>Hydrologie Appliquée Aux Petits Bassins
Ruraux</em>. Cemagref, Antony.
</div>
<div id="ref-mouelhi_stepwise_2006" class="csl-entry">
Mouelhi, S., C. Michel, C. Perrin, and V. Andréassian. 2006.
<span>“Stepwise Development of a Two-Parameter Monthly Water Balance
Model.”</span> <em>Journal of Hydrology</em> 318 (1–4): 200–214. <a
href="https://doi.org/10.1016/j.jhydrol.2005.06.014">https://doi.org/10.1016/j.jhydrol.2005.06.014</a>.
</div>
<div id="ref-nash_river_1970" class="csl-entry">
Nash, J. E., and J. V. Sutcliffe. 1970. <span>“River Flow Forecasting
Through Conceptual Models Part <span>I</span> – <span>A</span>
Discussion of Principles.”</span> <em>Journal of Hydrology</em> 10 (3):
282–90. <a
href="https://doi.org/10.1016/0022-1694(70)90255-6">https://doi.org/10.1016/0022-1694(70)90255-6</a>.
</div>
<div id="ref-oudin_which_2005" class="csl-entry">
Oudin, L., F. Hervieu, C. Michel, C. Perrin, V. Andréassian, F. Anctil,
and C. Loumagne. 2005. <span>“Which Potential Evapotranspiration Input
for a Lumped Rainfall–Runoff Model?: <span>Part</span>
2-<span>Towards</span> a Simple and Efficient Potential
Evapotranspiration Model for Rainfall–Runoff Modelling.”</span>
<em>Journal of Hydrology</em> 303 (1–4): 290–306. <a
href="https://doi.org/10.1016/j.jhydrol.2004.08.026">https://doi.org/10.1016/j.jhydrol.2004.08.026</a>.
</div>
</div>
</div>

<footer>
  <div style="float:left"><img src="fig/logo_republique_francaise_CMJN.svg" alt="airGR logo" height=50px style="margin-top:-20px" /></div>
  <div style="float:right">Developed by INRAE&nbsp;<a href="https://webgr.inrae.fr/eng/">Catchment Hydrology Research Group</a>&nbsp;&#x2013; Antony, France</div>
</footer>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
